### `지도 학습( Supervised Learning )`

→ 레이블이 지정된 훈련 데이터 기반으로 모델 구축 

- 각 행은 `입력 변수`와 원하는 `대상 변수`로 구성됨
- ex ) 타이타닉 데이터의 성별, 나이, 객실 클래스 → 승객의 생존 여부

 ## 데이터 전처리


In [2]:
import numpy as np
from sklearn import preprocessing

# 샘플 데이터 정의
input_data = np.array([[5.1, -2.9, 3.3],
                        [-1.2, 7.8, 6.1],
                        [3.9, 0.4, 2.1],
                        [7.3, 9.9, -4.5]])

### 이진화

In [4]:
# 데이터 이진화
# 내장 메서드 사용, 임계값 = 2.1
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)
# 2.1보다 큰 값은 모두 1이 되고 나머지는 모두 0이 됨


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 1. 0.]]


### 평균 제거

In [5]:
# 평균과 표준 편차 츌력
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# 평균 제거
data_scaled = preprocessing.scale(input_data)
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))


BEFORE:
Mean = [3.775 3.8   1.75 ]
Std deviation = [3.12039661 5.23593354 3.8894087 ]

AFTER:
Mean = [1.11022302e-16 0.00000000e+00 5.55111512e-17]
Std deviation = [1. 1. 1.]


### 스케일링( Scaling )

In [8]:
# 최소-최대 스케일링 
data_scaled_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1)) # 0~1 범위
data_scaled_minmax = data_scaled_minmax.fit_transform(input_data)
print("\nMin max scaled data: \n", data_scaled_minmax) 


Min max scaled data: 
 [[0.74117647 0.         0.73584906]
 [0.         0.8359375  1.        ]
 [0.6        0.2578125  0.62264151]
 [1.         1.         0.        ]]


### 정규화( Normalization )

In [9]:
# 데이터 정규화
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", dara_normalized_l1)
print("\nL1 normalized data:\n", dara_normalized_l2)


L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629  0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553  0.4562212  -0.20737327]]


NameError: name 'dara_normalized_l2' is not defined